# Generated by Django 5.0.4 on 2024-05-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVATE'), ('inactive', 'INACTIVE')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('requested_bottle_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('in_progress', 'IN PROGRESS'), ('delivered', 'DELIVERED')], max_length=20, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estimated_durartion', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bottle_quantity', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('bottle_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('on_route', 'ON ROUTE'), ('out_of_service', 'OUT OF SERVICE')], max_length=20, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
